# Generated by Django 5.2.3 on 2025-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('job', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
        ),
    ]
